service: email-service

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  environment:
    SMTP_HOST: ${env:SMTP_HOST, 'smtp.gmail.com'}
    SMTP_PORT: ${env:SMTP_PORT, '587'}
    SMTP_USER: ${env:SMTP_USER, ''}
    SMTP_PASS: ${env:SMTP_PASS, ''}

plugins:
  - serverless-offline

functions:
  sendEmail:
    handler: handler.send_email
    events:
      - http:
          path: email/send
          method: post
          cors: true
